INP_IMAGE_DIM = 4096
INP_TXT_DIM = 81
N_TAGS = 81

HIDDEN_IMG_DIM = 80
HIDDEN_TXT_DIM = 80
HIDDEN_CON_DIM = HIDDEN_IMG_DIM + HIDDEN_TXT_DIM
SHARED_DIM = 100
N_EXAMPLE = 28000
N_TEST = 2000
TOP_N = 10

STOP_I2T = 0
STOP_T2I = 0
ITER = 0

DATA_ROOT = "/home/nda/Workspace/Python/Tensor/it6311-cross-media/mae/NUS-WIDE-Lite-dataset"
PATH_FEATURES = "%s/train_features.txt"%DATA_ROOT
PATH_LABELS = "%s/train_labels.txt"%DATA_ROOT

